// Variables
@localhost = http://localhost:4000/project

### Crear un proyecto
POST {{localhost}}
Content-Type: application/json
// Aqui va el auth-token: token

// Objeto que se envia al servidor
{
	"name": "",
}

### Buscar todos los proyectos
GET {{localhost}}
// Aqui va el auth-token: token

### Buscar un proyecto por ID
GET {{localhost}}/
// Aqui va el auth-token: token

### Actualizar un proyecto
PATCH {{localhost}}/
Content-Type: application/json
// Aqui va el auth-token: token

// Objeto que se envia al servidor
{
	"name": ""
}

### Eliminar un proyecto
DELETE {{localhost}}/
