// Variables
@localhost = http://localhost:4000/report

### Crear un reporte
POST {{localhost}}
Content-Type: application/json
// Aqui va el auth-token: token

// Objeto que se envia al servidor
{
	"current": ,
	"cable_width":"",
	"pipe_diameter":"",
	"protection_device":,
	"voltaje_drop": ,
	"circuit": {}
}

### Crear un reporte previo
POST {{localhost}}/listForm
Content-Type: application/json
// Aqui va el auth-token: token

// Objeto que se envia al servidor
{
	"loadType": 1,
	"power": 8000,
	"distance": 15,
	"powerFactor": 0.8,
	"voltageDrop": 3,
	"aisolation": 1,
	"temperature": 30,
	"loadPhases": 2,
	"perPhase": 1,
	"feeder_include_neutral_wire": true,
	"pipe_material": 0,
	"system_voltage": 208
}


### Buscar todos los reportes
GET {{localhost}}
// Aqui va el auth-token: token

### Buscar un reporte por ID
GET {{localhost}}/
// Aqui va el auth-token: token

### Actualizar un circuito
PATCH {{localhost}}/
Content-Type: application/json
// Aqui va el auth-token: token

// Objeto que se envia al servidor
{
	"current": ,
	"cable_width":"",
	"pipe_diameter":"",
	"protection_device":,
	"voltaje_drop": ,
	"circuit": {}
}

### Eliminar un reporte
DELETE {{localhost}}/
